spring.application.name=SeatLockSystem

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/seatlock
spring.datasource.username=postgres
spring.datasource.password=lalit
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Connection
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Jackson support for Java 8 Date/Time (important for DTOs)
# look for suitable Jackson feature